feat: add test to functions deployment

diff --git a/.github/workflows/main_az-runner.yml b/.github/workflows/main_az-runner.yml
--- a/.github/workflows/main_az-runner.yml
+++ b/.github/workflows/main_az-runner.yml
@@ -9,22 +9,25 @@ on:
         - '*.json'
         - '.github/workflows/deploy.yml'
         - '.github/workflows/main_az-runner.yml'
-        - '*Func'
+        - 'startup/*'
   workflow_call:
     inputs:
-      slot:
+      no-test:
         required: false
-        type: string
+        type: boolean
+        default: true
   workflow_dispatch:
     inputs:
-      slot:
+      no-test:
         required: false
-        type: string
+        type: boolean
+        default: true
 
 jobs:
   deploy:
     name: deploy functions
     runs-on: windows-latest
+    environment: azure-functions
     permissions:
       id-token: write
     concurrency:
@@ -46,5 +49,29 @@ jobs:
         id: fa
         with:
           app-name: ${{ vars.AZ_FUNCTION_APP_NAME }}
-          slot-name: ${{ inputs.slot || 'production' }}
+          slot-name: 'production'
           package: '.'
+  
+  test:
+    name: invoke webhook
+    needs: deploy
+    if: !inputs.no-test
+    runs-on:
+      - self-hosted
+      - azure
+      - production
+    steps:
+      - name: print output
+        run: echo "Test successful"
+
+  check:
+    name: check final state
+    runs-on: ubuntu-latest
+    needs: test
+    if: !inputs.no-test
+    steps:
+      - name: fail if test runner failed to complete
+        if: needs.test.result != 'success'
+        run: |
+          echo "Test runner was probably cancelled or failed otherwise."
+          exit 1
